name: PHP Linting (Pint)
on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  php-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute type checking
        run: ./vendor/bin/pint -v --test src
